# config specific to production environment
configure do
  ## worker number can be detected by CPU count
  # set :workers, 4

  # enable Nyara.logger
  set :logger, true

  # assets manifest is generated by `rake assets:build`
  set :manifest, (YAML.load_file Nyara.project_path 'public/manifest.yml')

  # todo after_fork
end
